version: '3'

services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: sfb-db
      MYSQL_USER: sfb-user
      MYSQL_PASSWORD: sfb-pass
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    container_name: backend_app
    build:
      dockerfile: .Dockerfile
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: sfb-db
      DB_USERNAME: sfb-user
      DB_PASSWORD: sfb-pass
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    entrypoint:
      - "./docker-startup.sh"
